// @ts-check

/**
 * Due percorsi distinti, deliberatamente separati.
 *
 * «Fondamenti» è la guida che si legge prima di contribuire: parte da zero e
 * non presuppone né competenza clinica né competenza sui protocolli sanitari.
 * «Documentazione» è il progetto: presuppone i fondamenti e non li ripete.
 *
 * Tenerli separati nella navigazione è una scelta editoriale, non estetica.
 * Chi arriva senza contesto ha bisogno di sapere da dove si comincia, e chi il
 * contesto ce l'ha non deve attraversarlo di nuovo ogni volta.
 */

/** @param {string} dirName */
const area = (label, dirName, description) => ({
  type: 'category',
  label,
  link: {type: 'generated-index', title: label, description},
  items: [{type: 'autogenerated', dirName}],
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guidaSidebar: [
    {
      type: 'category',
      label: 'Guida dei fondamenti',
      link: {
        type: 'generated-index',
        title: 'Guida dei fondamenti',
        description:
          "Tutto ciò che serve sapere prima di contribuire, a partire da zero: il sistema sanitario, il dato clinico, gli standard di interoperabilità, i fondamenti clinici, quelli informatici e il quadro regolatorio. Non dà nulla per scontato.",
      },
      items: [{type: 'autogenerated', dirName: '10_fondamenti'}],
    },
  ],

  progettoSidebar: [
    area('Panoramica', '00_overview', "Che cos'è Telemedic, a chi serve e come è organizzata la documentazione."),
    area('Tecnica', '01_technical', 'Come è realizzato il sistema: stack, backend, persistenza, frontend, media, osservabilità, qualità e rilascio.'),
    area('Architettura', '02_architecture', 'Contesti delimitati, modello di dominio, modello dati, multi-tenancy, eventi, tracciamento e viste di deployment.'),
    area('Funzionale', '03_functional', 'Attori, requisiti, casi d’uso, regole di business, allarmi, accessibilità e ciò che resta fuori perimetro.'),
    area('Protocolli', '04_protocols', 'FHIR, documenti clinici, HL7 v2, IHE, API di progetto, eventi, identità, tempo reale e prove di conformità.'),
    area('Dominio', '05_domain', 'Il linguaggio ubiquo e il modello del dominio sanitario, prima del codice.'),
    area('Sicurezza', '06_security', 'Modello di minaccia, identità e accessi, protezione dei dati, tracciamento, catena di fornitura e risposta agli incidenti.'),
    area('Integrazione', '07_integration', 'Come un sistema di terze parti si integra con Telemedic, e quando una modalità è la scelta sbagliata.'),
    area('Conformità', '08_compliance', 'Inquadramento normativo, qualificazione, sistema qualità, gestione del rischio e percorso di certificazione.'),
    area('Roadmap', '09_roadmap', 'Traguardi datati, criteri di completamento verificabili, primo rilascio utilizzabile e registro dei rischi di programma.'),
    {
      type: 'category',
      label: 'Decisioni architetturali',
      link: {
        type: 'generated-index',
        title: 'Decisioni architetturali',
        description:
          'Ogni decisione strutturale è registrata con il contesto in cui è stata presa, le alternative scartate e le conseguenze accettate. Una decisione senza le sue conseguenze è un’opinione.',
      },
      items: [{type: 'autogenerated', dirName: 'adr'}],
    },
  ],
};

export default sidebars;
